receivers:
  filelog/confluence-access:
    include:
      - /hostfs/var/mnt/data/confluence-logs/confluence_access.*.log
    exclude:
      - /hostfs/var/mnt/data/confluence-logs/confluence_access.202[0-5]-*.log
    start_at: end
    storage: file_storage
    resource:
      service.name: confluence-access
    operators:
      - type: regex_parser
        regex: '\[(?P<timestamp>[^\]]+)\].*"\s+(?P<status_class>\d)\d{2}\s'
        timestamp:
          parse_from: attributes.timestamp
          layout: '%d/%b/%Y:%H:%M:%S %z'
        on_error: send
      - type: severity_parser
        parse_from: attributes.status_class
        mapping:
          info: "2"
          info2: "3"
          warn: "4"
          error: "5"
        on_error: send
service:
  pipelines:
    logs/confluence-filelog:
      receivers:
        - filelog/confluence-access
      processors: [resourcedetection, transform/severity-text, batch]
      exporters: [otlp]
