desired_hostname: fbshs1.zt.foreningenbs.no

zerotier_host_ip: "172.25.12.4"
zerotier_host_ip_cidr: "172.25.12.4/16"
zerotier_network_id: a84ac5c10a9c7522

docker_subnet: "172.25.0.0/16"
docker_ip_range: "172.25.29.0/24"

host_type: fcos
data_dir: /var/mnt/data

zincati_start_time: "04:00"
