name: Run Checkly
on:
  workflow_call:
    inputs:
      tags:
        description: "Optional tag filter passed to Checkly test runs"
        required: true
        type: string

env:
  CHECKLY_ACCOUNT_ID: ${{ vars.CHECKLY_ACCOUNT_ID }}
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  FBS_TEST_USERNAME: ${{ vars.FBS_TEST_USERNAME }}
  FBS_TEST_PASSWORD: ${{ secrets.FBS_TEST_PASSWORD }}

defaults:
  run:
    working-directory: ./checkly

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: "checkly/package.json"
      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "checkly/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm checkly -v
      - run: pnpm checkly test --reporter=github --record --tags "${{ inputs.tags }}"
      - run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
        if: always()
