name: Run Checkly
on:
  workflow_call:
    inputs:
      tags:
        description: "Optional tag filter passed to Checkly test runs"
        required: true
        type: string
      retries:
        description: "Number of retries for Checkly test runs"
        required: false
        type: number
        default: 0

env:
  CHECKLY_ACCOUNT_ID: ${{ vars.CHECKLY_ACCOUNT_ID }}
  CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
  FBS_TEST_USERNAME: ${{ vars.FBS_TEST_USERNAME }}
  FBS_TEST_PASSWORD: ${{ secrets.FBS_TEST_PASSWORD }}

defaults:
  run:
    working-directory: ./checkly

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          package_json_file: "checkly/package.json"
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: "24"
          cache: "pnpm"
          cache-dependency-path: "checkly/pnpm-lock.yaml"
      - run: pnpm install --frozen-lockfile
      - run: pnpm checkly -v
      - run: pnpm checkly test --reporter=github --record --tags "${{ inputs.tags }}" --retries ${{ inputs.retries }}
      - run: cat checkly-github-report.md > $GITHUB_STEP_SUMMARY
        if: always()
